default_install_hook_types:
- pre-commit
- commit-msg
- post-checkout
- post-merge

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: ["--markdown-linebreak-ext=md"]

# Run linting and uv hooks as system hooks
- repo: local
  hooks:
    - id: ruff
      name: "ruff: lint"
      entry: uv run ruff check src
      language: system
      pass_filenames: false
      stages:
        - pre-commit
    - id: ruff-format
      name: "ruff: format"
      language: system
      entry: uv run ruff format src
      pass_filenames: false
      stages:
        - pre-commit
    - id: ruff-sort-imports
      name: "ruff: sort imports"
      language: system
      entry: uv run ruff check --fix --select I
      pass_filenames: false
      stages:
        - pre-commit
    - id: mypy
      name: mypy
      language: system
      entry: uv run mypy src
      pass_filenames: false
      stages:
        - pre-commit
    - id: uv-sync
      name: "uv: sync"
      language: system
      entry: uv sync --frozen
      pass_filenames: false
      stages:
        - post-merge
        - post-checkout
    - id: uv-lock
      name: "uv: lock"
      entry: uv lock
      language: system
      files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
      pass_filenames: false
