default_install_hook_types:
- pre-commit
- commit-msg
- post-checkout
- post-merge

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args: ["--markdown-linebreak-ext=md"]

# linting
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.2
  hooks:
    - id: ruff
    - id: ruff-format

# static type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    files: ^src/
    args: [--config-file, pyproject.toml]
    additional_dependencies:
    - click
    - loguru
    - importlib_resources
    - shellingham
    - types-psutil
    - types-pygit2

- repo: https://github.com/pdm-project/pdm
  rev: '2.22.2'
  hooks:
  - id: pdm-lock-check
  - id: pdm-sync
    verbose: true
    args: ["--clean", "--venv", "in-project"]
