# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PyGWT - Python Git Worktree

repo_name: Bubichoo-Teitichoo/pygwt
repo_url: https://github.com/Bubichoo-Teitichoo/pygwt

watch:
  - .

nav:
  - Home: index.md
  - Changelog: changelog.md
  - CLI Reference: cli.md

extra:
  version:
    provider: mike

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  font:
    text: Roboto
    code: JetBrains Mono
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.sections
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
- search

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - callouts
  - def_list
  - footnotes
  - github-callouts
  - md_in_html
  - mkdocs-click
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
