name: Bump Version Number

on:
  workflow_dispatch:


jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run:
        pip install pdm
        pdm sync
    - name: Bump Version number
      run:
        pdm bump
        git push
        git push --tags
        git push origin gh-pages
