name: Bump Version Number

on:
  workflow_dispatch:


jobs:
  bump:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
        fetch-tags: true
    - name: Configure git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - uses: jdx/mise-action@v4
    - name: Bump Version number
      run: |
        mise bump
        git push
        git push --tags
