name: Deploy Docs

on:
  push:
    branches:
    - main
    tags:
    - "*"
  workflow_run:
    workflows:
      - Bump Version Number
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Configure git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.10"
    - name: Build and deploy docs (branch)
      if: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}
      run: |
        uv run git-changelog
        uv run --group docs mike deploy --push --update-aliases --alias-type redirect "dev"
    - name: Build and deploy docs (tag)
      if: ${{ github.event_name == 'push' && github.ref_type == 'tag' || github.event_name == 'workflow_run' }}
      run: |
        version="$(uv version --short | sed -E 's/([0-9]+)\.([0-9]+)\.[0-9]+/\1.\2.x/g')"
        uv run --group docs mike delete "dev"
        uv run --group docs mike deploy --push --update-aliases --alias-type redirect $version latest

