name: Deploy Docs

on:
  push:
    branches:
    - main
    tags:
    - "*"

concurrency:
  group: ${{ github.workflow }
  cancel-in-progress: false

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Configure git user
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run:
        pdm install --skip post_install
    - name: Build and deploy docs (branch)
      if: contains(github.ref, 'refs/heads')
      run: |
        eval $(pdm venv activate)
        git-changelog
        mike deploy --push --update-aliases --alias-type redirect "dev"
    - name: Build and deploy docs (tag)
      if: contains(github.ref, 'refs/tags')
      run: |
        eval $(pdm venv activate)
        version="$(cz version --project | sed -E 's/([0-9]+)\.([0-9]+)\.[0-9]+/\1.\2.x/g')"
        mike remove "dev"
        mike deploy --push --update-aliases --alias-type redirect $version latest
