name: Deploy Docs

on:
  push:
    tags:
       - '\d+\.\d+\.\d+'

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run:
        pdm install --skip post_install
    - name: Bump Version number
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        eval $(pdm venv activate)
        mike deploy --push --update-aliases --alias-type redirect $(cz version --project) latest
