name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: pdm install --skip post_install
    - name: Lint (Ruff)
      env:
        RUFF_OUTPUT_FORMAT: github
      run:
        pdm lint
